version: '3.8'

services:
  mcp-host-runner:
    build: .
    container_name: mcp-host-runner
    ports:
      - "8001:8001"
    environment:
      - HOST=0.0.0.0
      - PORT=8001
      - LOG_LEVEL=INFO
      - ENVIRONMENT=production
    volumes:
      - ./logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock  # Docker socket for container management (if needed)
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Redis (선택적 - 캐싱용)
  # redis:
  #   image: redis:7-alpine
  #   container_name: mcp-redis
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped