services:
  - type: web
    name: mcp-host-runner
    env: python
    plan: free
    buildCommand: |
      export TERM=dumb
      pip install --no-color --quiet -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TERM
        value: dumb